VehicleRouting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('ai_vehicle/', include('ai_vehicle.urls')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns  += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from .views import *

from home import views

urlpatterns = [
    path('', views.upload_orders, name='upload_orders'),
    path('delete-all-orders/', delete_all_orders, name='delete_all_orders'),
    path('signup', views.signuppage, name='signup'),
    path('customers', views.customers, name='customers'),
    path('drivers', views.drivers, name='drivers'),
    path('drivers/<int:pk>', views.drivers, name='driver_single'),
    path('payments', views.payments, name='payments'),
    path('vehicles', views.vehicles, name='vehicles'),
    path('reset_assinged_trucks', views.reset_assinged_trucks, name='reset_assinged_trucks'),
    path('escalationteam', views.escalationteam, name='escalationteam'),
    path('customer_single_order/<int:pk>', views.customer_single_order, name='customer_single_order'),
    path('switchAccounts', views.switchAccounts, name='switchAccounts'),
    path('reports', views.reports, name='reports'),
    path('post_reports', views.post_reports, name='post_reports'),
    path('search_orders', views.search_orders, name='search_orders'),
    path('edit_order', views.edit_order, name='edit_order'),

    

    
    path('search_customers', views.search_customers, name='search_customers'),
    path('fetchinprocess', views.fetchinprocess, name='fetchinprocess'),
    
    path('add_service/<int:pk>', views.add_service, name='add_service'),
    path('delete_vehicle/<int:pk>', views.delete_vehicle, name='delete_vehicle'),
    path('edit_vehicle/<int:pk>', views.edit_vehicle, name='edit_vehicle'),
    path('admin_single_vehicle/<int:pk>', views.admin_single_vehicle, name='admin_single_vehicle'),

    
    path('single_customer/<int:pk>', views.single_customer, name='single_customer'),
    path('single_order/<int:pk>', views.single_order, name='single_order'),
    path('report_issue/<int:pk>', views.report_issue, name='report_issue'),

    

    



]

home/models.py
from django.db import models
# from ai_vehicle.models import routedata

class Truck(models.Model):
    TRUCK_OWNER = [
        ('owned', 'owned'),
        ('rented', 'rented')]
    TRUCK_TYPE_CHOICES = [
        ('Flatbed', 'Flatbed'),
        ('Box', 'Box'),
        ('Tanker', 'Tanker'),
        ('Refrigerated', 'Refrigerated'),
        ('Car Carrier', 'Car Carrier'),
    ]
    STATUS_CHOICES = [
        ('available', 'available'),
        ('not_available', 'not_available'),
        ('in_service', 'In Service'),
        ('maintenance', 'Under Maintenance'),
    ]
    LICENSE_TYPE_CHOICES = [
        ('C', 'Class C - Light Truck'),
        ('B', 'Class B - Medium Truck'),
        ('A', 'Class A - Heavy Truck'),
    ]

    truck_name                          = models.CharField(max_length=255)
    truck_owner                         = models.CharField(max_length=6, choices=TRUCK_OWNER,default='owned')
    truck_type                          = models.CharField(max_length=50, choices=TRUCK_TYPE_CHOICES,default='Tanker')
    truck_image                         = models.ImageField(upload_to='trucks', null=True, blank=True)
    truck_number                        = models.CharField(max_length=100, unique=True)
    capacity                            = models.PositiveIntegerField()  # Assuming capacity is in kilograms or liters
    make                                = models.CharField(max_length=100,null=True, blank=True)
    model                               = models.CharField(max_length=100,null=True, blank=True)
    year                                = models.PositiveIntegerField(null=True, blank=True)
    mileage                             = models.PositiveIntegerField(verbose_name="Mileage (in km)",null=True, blank=True)
    license_type                        = models.CharField(max_length=2, choices=LICENSE_TYPE_CHOICES, verbose_name="Required License Type",null=True, blank=True,default='B')
    truck_order                         = models.PositiveIntegerField(null=True, blank=True)
    cost_per_km                         = models.DecimalField(max_digits=10, decimal_places=2)
    status                              = models.CharField(max_length=20, choices=STATUS_CHOICES, default='available',null=True, blank=True)
    purchase_date                       = models.DateField(null=True, blank=True)
    last_service_date                   = models.DateField(null=True, blank=True)

    driver_name                         = models.CharField(max_length=255)
    driver_email                        = models.EmailField(max_length=100)
    contact_number                      = models.CharField(max_length=100, null=True, blank=True, default=9876543213)
    driver_order                        = models.PositiveIntegerField(null=True, blank=True,default=0)
    on_time_deliveries                  = models.PositiveIntegerField(null=True, blank=True,default=0)
    late_deliveries                     = models.PositiveIntegerField(null=True, blank=True,default=0)

    driver_travel                       = models.PositiveIntegerField(null=True, blank=True,default=0)
    service_travel_km                       = models.PositiveIntegerField(null=True, blank=True,default=0)


    fuel                                = models.PositiveIntegerField(null=True, blank=True,default=0)
    deleverd_load                       = models.PositiveIntegerField(null=True, blank=True,default=0)
    languages                           = models.CharField(max_length=100,null=True, blank=True,default='English')

    
    available                           = models.BooleanField(default=True)
    on_service                           = models.BooleanField(default=False)



    routedata                           = models.ForeignKey('ai_vehicle.routedata', null=True, blank=True, on_delete=models.PROTECT)
    warehouse                           = models.ForeignKey('ai_vehicle.HeadQuarter', on_delete=models.PROTECT, null=True, blank=True,default=1)

    start_time                          = models.TimeField(null=True, blank=True)
    end_time                            = models.TimeField(null=True, blank=True)

    def __str__(self): return f"{self.truck_name} ({self.truck_number}) | avl-{self.available} | onreoute-{bool(self.routedata)} | warehouse - {self.warehouse.name}"

    def get_license_type_display(self):
        license_mapping = {
            'C': 'Class C - Light Truck',
            'B': 'Class B - Medium Truck',
            'A': 'Class A - Heavy Truck',
        }
        return license_mapping.get(self.license_type, 'Unknown License Type')






class ServiceOrPart(models.Model):
    SERVICE_TYPE_CHOICES = [
        ('service', 'Service Description'),
        ('part', 'Part Changed'),
    ]
    
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=10, choices=SERVICE_TYPE_CHOICES)

    def __str__(self):
        return f"{self.name} ({self.type})"


class ServiceRecord(models.Model):
    truck = models.ForeignKey(Truck, on_delete=models.CASCADE, related_name='services')
    service_date = models.DateField()
    service_description = models.ManyToManyField(ServiceOrPart, related_name='service_records', limit_choices_to={'type': 'service'}, blank=True)
    parts_changed = models.ManyToManyField(ServiceOrPart, related_name='parts_records', limit_choices_to={'type': 'part'}, blank=True)
    cost = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Total Service Cost (in USD)", default=300)

    def __str__(self):
        return f"Service for {self.truck} on {self.service_date}"



class Order(models.Model):
    PRODUCT_STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('completed', 'Completed'),
        ('canceled', 'Canceled'),
        ('shipped', 'Shipped'),
        ('delivered', 'delivered'),
    ]
    PAYMENT_STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('completed', 'Completed'),
        ('canceled', 'Canceled'),
        ('due', 'due'),
        ('past_due', 'past_due'),
        ('escalation_pending', 'escalation_pending'),
    ]

    email                               = models.EmailField()
    cname                               = models.CharField(max_length=75,default='Alex')
    product_name                        = models.CharField(max_length=255)
    quantity                            = models.PositiveIntegerField(default=0)
    from_location                       = models.CharField(max_length=255, blank=True, null=True)
    destination                         = models.CharField(max_length=255)
    payment_amount                      = models.DecimalField(max_digits=10, decimal_places=2)# Adjust max_digits and decimal_places as needed
    order_status                        = models.CharField(max_length=20, choices=PRODUCT_STATUS_CHOICES, default='pending')
    payment_status                      = models.CharField(max_length=20, choices=PAYMENT_STATUS_CHOICES, default='pending')
    send_email_count                    = models.PositiveIntegerField(default=0)
    created_at                          = models.DateTimeField(null=True, blank=True)  # Automatically set when the order is created
    updated_at                          = models.DateTimeField(null=True, blank=True) 
    delivered_date                      = models.DateTimeField(null=True, blank=True)
    due_reminder_sent_date              = models.DateTimeField(null=True, blank=True)
    past_due_reminder_sent_date         = models.DateTimeField(null=True, blank=True)
    final_reminder_sent_date            = models.DateTimeField(null=True, blank=True)
    payment_date                        = models.DateField(null=True, blank=True)  # Date when payment is sucessfully donee
    due_payment_date                    = models.DateField(null=True, blank=True)  # Date by which payment should be made
    past_due_payment_date               = models.DateField(null=True, blank=True)  # Date by which payment is late
    lat                                 = models.CharField(max_length=15, blank=True, null=True)
    long                                = models.CharField(max_length=15, blank=True, null=True)
    late_payment_status                 = models.BooleanField(default=False)  # To indicate if the payment is late
    due_days                            = models.PositiveIntegerField(default=0)
    warehouse                           = models.ForeignKey('ai_vehicle.HeadQuarter', on_delete=models.PROTECT, blank=True, null=True)
    assigned_truck                      = models.ForeignKey('Truck', blank=True, null=True, on_delete=models.PROTECT)


    route_distance                      = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=2, help_text="Distance in kilometers")
    delivery_time                       = models.DurationField(null=True, blank=True, help_text="Time taken for the delivery")
    fuel_consumption                    = models.DecimalField(null=True, blank=True, max_digits=5, decimal_places=2, help_text="Fuel consumed in liters")
    on_time_delivery                    = models.BooleanField(null=True, blank=True, default=True, help_text="Was the delivery on time?")

    fuel_savings                        = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=2, help_text="Fuel savings in dollars")
    vehicle_maintenance_savings         = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=2, help_text="Savings in vehicle maintenance")

    hours_worked                        = models.DecimalField(null=True, blank=True, max_digits=5, decimal_places=2, help_text="Hours worked by the driver")
    idle_time                           = models.DurationField(null=True, blank=True, help_text="Idle time during the delivery route")
    route_adherence                     = models.BooleanField(null=True, blank=True, default=True, help_text="Did the driver adhere to the planned route?")

templates/home/orderemail.html
<!-- welcome.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmation of order</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');

        body,p,h1,h2,h3,h4,h5,h6,a,span,strong {
            font-family: "Plus Jakarta Sans", sans-serif;
        }
    </style>
</head>
<body>
    <table class="main" width="100%" cellpadding="0" cellspacing="0" style="box-sizing: border-box; font-size: 14px;  border: 0;">
        <tbody>
            <tr style="box-sizing: border-box; font-size: 14px; margin: 0;">
                <td align="center">
                    <table width="500" cellpadding="0" cellspacing="0" style="border:1px solid #eee; box-sizing: border-box; font-size: 14px; margin: 0;">
                        <tbody>
                            <tr>
                                <td align="left"  style="background-color: #000; padding: 30px 20px; ">
                                    <a href="#" style="font-size:20px;color:#fff;text-decoration:none;font-weight:700;font-family: 'Playfair Display', serif;">
                                         <img src="https://engagedcelebration.com/assets/Logo-a12-1c4ad440.png" style="width:250px;"> 
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="1"  class="content-block" style="font-size: 14px; padding: 20px 20px 10px;letter-spacing:0.3px;line-height:25px;" >
                                    <p style="font-size: 14px; vertical-align: top; margin: 0; padding: 0px 0px 10px; color: #333;">Hi  <strong>{{user}}</strong> </p>
                                    <p style="font-size: 14px; vertical-align: top; margin: 0; padding: 0px 0px 10px; color: #333;">

                                       
                                            {{content}}
                                      
                                       

                                    </p>
                                    <p style="font-size: 14px; vertical-align: top; margin: 0; padding: 0px 0px 10px; color: #333;"><a href="http://74.208.28.29/switchAccounts" style="color:#738ea5;font-weight:500;text-decoration:none;border:1px solid #b47f1c;padding:5px 10px; color:#fff;background:#b47f1c;font-size:12px;">Login</a>
                                    </p>                                    
                                </td>
                                
                            </tr>                        
                            <tr style="box-sizing: border-box; font-size: 14px; margin: 0;">
                                <td class="content-block" style="box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 20px 20px 20px;" valign="top">
                                    <p style="margin:0; padding-bottom:5px;color:#252525;"><strong>Best wishes,
                                    </strong></p>
                                    <p style="margin:0; padding-bottom:5px;color:#252525;">Vehicle Routing  </p>
                                </td>
                            </tr>
                            <tr style="box-sizing: border-box; font-size: 14px; margin: 0;">
                                <td class="content-block" style="text-align: center;box-sizing: border-box; font-size: 14px; color: #fff; vertical-align: top; margin: 0; padding: 15px 20px;background-color:#222224;" valign="top">
                                    © 2024 Vehicle routers
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
</body>
</html>

templates/home/single-order-team.html
    {% extends 'home/base-not-header.html' %}
    {% load static %}
    {% block content %}
    
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                        <h4 class="mb-sm-0 font-size-18">Customer Details</h4>
                    </div>
                </div>
            </div>
    
            <div class="row">
                <div class="col-md-7">
                    <div class="card h-100">
                        <div class="card-body">
                            <table id="orderTable" class="table ">
                                <thead class="table-light">
                                    <tr>
                                        <th>Field</th>
                                        <th>Details</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th>Product id</th>
                                        <td>#13A{{ order.id|title }}</td>
                                    </tr>
                                    <tr>
                                        <th>Name</th>
                                        <td>{{ order.cname|title }}</td>
                                    </tr>
                                    <tr>
                                        <th>Email</th>
                                        <td>{{ order.email }}</td>
                                    </tr>
                                    <tr>
                                        <th>Product Name</th>
                                        <td>{{ order.product_name }}</td>
                                    </tr>
                                    <tr>
                                        <th>Quantity</th>
                                        <td>{{ order.quantity }}</td>
                                    </tr>
                                    <tr>
                                        <th>Destination</th>
                                        <td>{{ order.destination }}</td>
                                    </tr>
                                    <tr>
                                        <th>Payment Amount</th>
                                        <td>${{ order.payment_amount }}</td>
                                    </tr>
                                    <tr>
                                        <th>Order Status</th>
                                        <td>{{ order.get_order_status_display }}</td>
                                    </tr>
                                    <tr>
                                        <th>Payment Status</th>
                                        <td>{{ order.get_payment_status_display }}</td>
                                    </tr>
                                    <tr>
                                        <th>Due Date</th>
                                        <td>{{ order.due_payment_date }}</td>
                                    </tr>
                                </tbody>
                            </table>
            

            
                           
                        </div>
                    </div>
                    <!-- Order Info Table with DataTable -->
                    
                </div>
    
                <div class="col-md-5">
                    <div class="card ">
                        <div class="card-body">
                            <div class="d-flex border-bottom ">
                                <div class="me-2 ">
                                    <h5 class="card-title mb-4">Order Activity</h5>
                                </div>
                            </div>
                            <div data-simplebar class="mt-2" >
                                <ul class="verti-timeline list-unstyled py-4">
                                    <li class="event-list active">
                                        <div class="event-timeline-dot">

                                            {% if order.send_email_count  == 0 %}
                                                <i class="bx bx-right-arrow-circle fa-2x text-secondary"></i>
                                                
                                            {% else %}
                                                <i class="bx bxs-check-circle fa-2x text-success"></i>
                                            {% endif %}


                                        </div>
                                        <div class="media">

                                
                                            <h5 class="font-size-18 fw-normal"> {% if order.delivered_date %}{{order.delivered_date}} {% endif %}
                                                <i class="bx bx-right-arrow-alt font-size-16 text-secondary align-middle ms-2"></i>
                                        </h5>
                                            <div class="media-body">
                                                <div>
                                                     <span class="font-weight-semibold font-size-16">Delivered</span>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    <li class="event-list">
                                        <div class="event-timeline-dot">
                                            {% if order.send_email_count  > 1 %}
                                            <i class="bx bxs-check-circle fa-2x text-success"></i>
                                           
                                            
                                        {% else %}
                                        <i class="bx bx-right-arrow-circle fa-2x text-secondary"></i>
                                           
                                        {% endif %}
                                        </div>
                                        <div class="media">
                                            <div class="me-3">
                                                <h5 class="font-size-18 fw-normal">
                                                    {% if order.due_reminder_sent_date %} {{order.due_reminder_sent_date}}  {% endif %}
                                                    <i class="bx bx-right-arrow-alt font-size-16 text-secondary align-middle ms-2"></i></h5>
                                            </div>
                                            <div class="media-body">
                                                <div>
                                                    <span class="font-weight-semibold font-size-16">Due Reminder</span>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    <li class="event-list">
                                        <div class="event-timeline-dot">
                                            {% if order.send_email_count > 2 %}
                                            <i class="bx bxs-check-circle fa-2x text-success"></i>
                                           
                                        {% else %}
                                        <i class="bx bx-right-arrow-circle fa-2x text-secondary"></i>
                                            
                                        {% endif %}
                                        </div>
                                        <div class="media">
                                            <div class="me-3">
                                                <h5 class="font-size-18 fw-normal">
                                                    {% if order.past_due_payment %} {{order.past_due_payment}}  {% endif %}
    
                                                    <i class="bx bx-right-arrow-alt font-size-16 text-secondary align-middle ms-2"></i></h5>
                                            </div>
                                            <div class="media-body">
                                                <div>
                                                    <span class="font-weight-semibold font-size-16">Last Due Reminder</span>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    <li class="event-list">
                                        <div class="event-timeline-dot">
                                            {% if order.send_email_count > 3 %}
                                            <i class="bx bxs-check-circle fa-2x text-success"></i>
                                            
                                            
                                        {% else %}
                                        <i class="bx bx-right-arrow-circle fa-2x text-secondary"></i>
                                           
                                        {% endif %}
                                        </div>
                                        <div class="media">
                                            <div class="me-3">
                                                <h5 class="font-size-18 fw-normal">
                                                    
    
                                                    {% if order.final_due_payment %} {{order.final_due_payment}}  {% endif %}
                                                    <i class="bx bx-right-arrow-alt font-size-16 text-secondary align-middle ms-2"></i></h5>
                                            </div>
                                            <div class="media-body">
                                                <div>
                                                    <span class="font-weight-semibold font-size-16">Last Reminder</span>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <div class="text-center justify-content-between d-flex py-2">
                                <a href="{% url 'escalationteam' %}" class="btn btn-md mr-2 btn-secondary">Back to Orders</a>
                                <a href="" class="btn btn-md mr-2 btn-danger">Black Listed</a>

                                <form method="post" action="{% url 'single_customer' order.id %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="payment_status" value="completed" />
                                    <input type="hidden" name="by_team_member" value="by_team_member" />
                                    <button type="submit" class="btn btn-md mr-2 btn-success">Payment Done</button>
                                </form>
    
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
    
    {% endblock %}